frase = "Python é uma linguagem excelente"
print('Py' in frase)
print('py' not in frase)
print('ing' in frase)
print(len(frase))
print(frase.lower())
print('py' in frase.lower())
print(frase)
print(frase.upper())
print(frase)
frase = frase.upper()
print(frase)
print(frase.split('a'.upper()))
