# Tuple
tupla = tuple()
tupla = ()
# print(type(tupla))
# print(dir(tupla))
# print(help(tupla))
tupla = ('um')
print(type(tupla))
tupla = ('um',)
print(type(tupla))
print(tupla[0])
cores = ('verde', 'amarelo', 'azul', 'azul', 'azul', 'branco')
print(cores[-1])
print(cores[:-1])
print(cores[0:2])
print(cores.index('amarelo'))
print(cores.count('azul'))
print(len(cores))
